version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          set -xu
          sh .circleci/scripts/build.sh
          docker images

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
