version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: |
          set -xu
          sh .circleci/scripts/build.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
