version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - run: |
          set -xu
          apk add --no-cache tree
          tree

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
